"""inventory: items, stock balances, stock movements

Revision ID: 39d04377bdfa
Revises: 9d0aa4717c2e
Create Date: 2026-08-22 15:41:55.431214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d04377bdfa'
down_revision: Union[str, None] = '9d0aa4717c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Enum('raw_material', 'work_in_progress', 'finished_good', 'consumable', name='itemtype'), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_item_tenant_sku')
    )
    op.create_table('stock_balances',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'item_id', name='uq_balance_plant_item')
    )
    op.create_table('stock_movements',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('movement_type', sa.Enum('receipt', 'issue', 'adjustment', 'transfer_in', 'transfer_out', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('stock_balances')
    op.drop_table('items')
    # ### end Alembic commands ###
