"""maintenance and quality: assets, work orders, inspections, defects

Revision ID: 907a3186093c
Revises: 4b30f27e646f
Create Date: 2026-08-22 15:53:07.099224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907a3186093c'
down_revision: Union[str, None] = '4b30f27e646f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('operational', 'down', 'maintenance', name='assetstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'code', name='uq_asset_plant_code')
    )
    op.create_table('inspections',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('inspected_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', name='inspectionresult'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspector_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', name='defectseverity'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='defectstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_work_orders',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_type', sa.Enum('preventive', 'corrective', 'inspection', name='workordertype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='workorderpriority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'cancelled', name='workorderstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_work_orders')
    op.drop_table('defects')
    op.drop_table('inspections')
    op.drop_table('assets')
    # ### end Alembic commands ###
