"""production: work centers, boms, bom components, production orders

Revision ID: e83caf7c1772
Revises: 6cfe955a8600
Create Date: 2026-08-22 15:48:09.387522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83caf7c1772'
down_revision: Union[str, None] = '6cfe955a8600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills_of_material',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('output_item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'output_item_id', 'version', name='uq_bom_tenant_output_version')
    )
    op.create_table('bom_components',
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('component_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_material.id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'component_item_id', name='uq_bom_component')
    )
    op.create_table('work_centers',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('capacity_per_hour', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'code', name='uq_work_center_plant_code')
    )
    op.create_table('production_orders',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('work_center_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_planned', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_completed', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='productionorderstatus'), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_material.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_orders')
    op.drop_table('work_centers')
    op.drop_table('bom_components')
    op.drop_table('bills_of_material')
    # ### end Alembic commands ###
